# Generated by Django 5.0.2 on 2024-03-01 07:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('url_image', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('article_shapo', models.TextField()),
                ('content', models.TextField()),
                ('data_plush', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.imagecontent')),
            ],
        ),
    ]
